//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aw_liec_gastos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_liecEntities : DbContext
    {
        public db_liecEntities()
            : base("name=db_liecEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fact_estatus> fact_estatus { get; set; }
        public virtual DbSet<fact_tipo_rubro> fact_tipo_rubro { get; set; }
        public virtual DbSet<fact_tipo_usuario> fact_tipo_usuario { get; set; }
        public virtual DbSet<inf_caja> inf_caja { get; set; }
        public virtual DbSet<inf_control_montos> inf_control_montos { get; set; }
        public virtual DbSet<inf_email_envio> inf_email_envio { get; set; }
        public virtual DbSet<inf_email_recepcion> inf_email_recepcion { get; set; }
        public virtual DbSet<inf_empresa> inf_empresa { get; set; }
        public virtual DbSet<inf_gastos> inf_gastos { get; set; }
        public virtual DbSet<inf_gastos_dep> inf_gastos_dep { get; set; }
        public virtual DbSet<inf_rubro> inf_rubro { get; set; }
        public virtual DbSet<inf_sepomex> inf_sepomex { get; set; }
        public virtual DbSet<inf_usuarios> inf_usuarios { get; set; }
    }
}
