//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aw_liec_gastos
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_email_recepcion
    {
        public System.Guid id_email_recepcion { get; set; }
        public Nullable<int> id_estatus { get; set; }
        public string email_recepcion { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.Guid> id_empresa { get; set; }
    
        public virtual fact_estatus fact_estatus { get; set; }
        public virtual inf_empresa inf_empresa { get; set; }
    }
}
