//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aw_liec_gastos
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_rubro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inf_rubro()
        {
            this.inf_control_montos = new HashSet<inf_control_montos>();
        }
    
        public System.Guid id_rubro { get; set; }
        public Nullable<int> id_estatus { get; set; }
        public Nullable<int> id_tipo_rubro { get; set; }
        public string rubro { get; set; }
        public Nullable<double> presupuesto { get; set; }
        public Nullable<int> minimo { get; set; }
        public Nullable<int> maximo { get; set; }
        public Nullable<double> presupuesto_extra { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.Guid> id_empresa { get; set; }
        public string codigo_rubro { get; set; }
        public string etiqueta_rubro { get; set; }
    
        public virtual fact_estatus fact_estatus { get; set; }
        public virtual fact_tipo_rubro fact_tipo_rubro { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_control_montos> inf_control_montos { get; set; }
        public virtual inf_empresa inf_empresa { get; set; }
    }
}
